modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "gain_friendship_from_melodies"
version = "${version}"
displayName = "Gain Friendship From Melodies"
authors = "LyquidQrystal"
description = '''
Enjoy the music with your Cobblemon!
'''
logoFile = "icon.png"

[[dependencies.gain_friendship_from_melodies]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gain_friendship_from_melodies]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gain_friendship_from_melodies]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gain_friendship_from_melodies]]
modId = "immersive_melodies"
type = "required"
versionRange = "[0.6.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "gain_friendship_from_melodies.mixins.json"